runtime: go
api_version: go1.9

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 128

handlers:
  - url: /favicon.ico
    static_files: asset/image/favicon.ico
    upload: asset/image/favicon.ico
  - url: /.*
    script: _go_app
    login: admin
    secure: always

env_variables:
  GIN_MODE: release
