services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  app:
    image: mackerel-server-go
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - SQL_MODE=debug
      - RUN_FIXTURE=true
      - HOST=root:secret@tcp(mackerel-server-go-mysql-1:3306)/
