version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  app:
    image: mackerel-server-go
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - DATA_SOURCE_NAME=root:secret@tcp(mackerel-server-go_mysql_1:3306)/
