version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  app:
    image: mackerel-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - GIN_MODE=release
      - DATA_SOURCE_NAME=root:secret@tcp(mackerel-api_mysql_1:3306)/
