name: tests

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go: ['1.15']
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup Go @ ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Unit Tests
        run: |
          make test
        
      - name: Integration Tests
        run: |
          make runmysql
          make godog

      - name: Codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
