name: tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit Tests
        run: |
          make test

      - name: Integration Tests
        run: |
          make runmysql
          make godog

      - name: Merge Test Coverage
        run: |
          make merge

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Package
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u itsubaki --password-stdin
          make package
